# Generated by Django 3.2.8 on 2022-02-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0002_data_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='filename',
        ),
    ]
