# Generated by Django 3.2.8 on 2022-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0003_remove_data_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
