# Generated by Django 3.2.8 on 2022-04-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0003_auto_20220403_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_count', models.IntegerField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serious_squad_app.data')),
            ],
        ),
    ]
