# Generated by Django 3.2.8 on 2022-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0004_reportflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportflag',
            name='report_comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='reportflag',
            name='reported_by',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
