# Generated by Django 3.2.8 on 2022-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0004_data_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
