# Generated by Django 3.2.8 on 2022-04-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0005_auto_20220417_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportflag',
            old_name='time',
            new_name='last_reported',
        ),
    ]
