# Generated by Django 3.2.8 on 2022-02-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0005_data_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='inappropiate_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_owner', models.IntegerField()),
                ('data_consumer', models.IntegerField()),
                ('data_approve_status', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serious_squad_app.data')),
            ],
        ),
    ]
