# Generated by Django 3.2.8 on 2022-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0006_rename_time_reportflag_last_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportflag',
            name='report_comment',
            field=models.CharField(max_length=2000),
        ),
    ]
