# Generated by Django 3.2.8 on 2022-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0006_auto_20220215_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='expires_on',
            field=models.DateTimeField(null=True),
        ),
    ]
