# Generated by Django 3.2.8 on 2022-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0010_data_universal_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='universal_flag',
        ),
        migrations.AddField(
            model_name='data',
            name='universal',
            field=models.CharField(default='Yes', max_length=255),
        ),
    ]
