# Generated by Django 3.2.8 on 2022-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0011_auto_20220301_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='specific_user',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='universal',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
