# Generated by Django 3.2.8 on 2022-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serious_squad_app', '0013_auto_20220316_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='specific_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
